// userData.js

const userDataList = [
    { name: "JohnDoe", birthdate: "1990", email: "john.doe@example.com" },
    { name: "JaneSmith", birthdate: "1985", email: "jane.smith@example.com" },
    { name: "BobJohnson", birthdate: "2000", email: "bob.johnson@example.com" },
    { name: "AliceWilliams", birthdate: "1995", email: "alice.williams@example.com" },
    { name: "CharlieBrown", birthdate: "1987", email: "charlie.brown@example.com" },
    { name: "DavidClark", birthdate: "1992", email: "david.clark@example.com" },
    { name: "EmilyDavis", birthdate: "1998", email: "emily.davis@example.com" },
    { name: "FrankMoore", birthdate: "1983", email: "frank.moore@example.com" },
    { name: "GraceAllen", birthdate: "1991", email: "grace.allen@example.com" },
    { name: "HenryLee", birthdate: "1986", email: "henry.lee@example.com" },
    { name: "IvyMiller", birthdate: "1994", email: "ivy.miller@example.com" },
    { name: "JackGreen", birthdate: "1989", email: "jack.green@example.com" },
    { name: "KateYoung", birthdate: "2001", email: "kate.young@example.com" },
    { name: "LiamKing", birthdate: "1988", email: "liam.king@example.com" },
    { name: "MiaWright", birthdate: "1993", email: "mia.wright@example.com" },
    { name: "NoahHill", birthdate: "1997", email: "noah.hill@example.com" },
    { name: "OliviaScott", birthdate: "1990", email: "olivia.scott@example.com" },
    { name: "PaulAdams", birthdate: "1984", email: "paul.adams@example.com" },
    { name: "QuinnBaker", birthdate: "1999", email: "quinn.baker@example.com" },
    { name: "RachelCarter", birthdate: "1985", email: "rachel.carter@example.com" },
    { name: "SamEvans", birthdate: "1996", email: "sam.evans@example.com" },
    { name: "TinaMartinez", birthdate: "1992", email: "tina.martinez@example.com" },
    { name: "UmaPerry", birthdate: "1990", email: "uma.perry@example.com" },
    { name: "VictorGomez", birthdate: "1983", email: "victor.gomez@example.com" },
    { name: "WendyFlores", birthdate: "1994", email: "wendy.flores@example.com" },
    { name: "XanderLong", birthdate: "1997", email: "xander.long@example.com" },
    { name: "YaraNelson", birthdate: "1989", email: "yara.nelson@example.com" },
    { name: "ZackHarris", birthdate: "1991", email: "zack.harris@example.com" },
    { name: "AmberTurner", birthdate: "1982", email: "amber.turner@example.com" },
    { name: "BenCollins", birthdate: "1986", email: "ben.collins@example.com" },
    { name: "ChloeGriffin", birthdate: "1993", email: "chloe.griffin@example.com" },
    { name: "DylanReed", birthdate: "1990", email: "dylan.reed@example.com" },
    { name: "EllaPowell", birthdate: "1988", email: "ella.powell@example.com" },
    { name: "FinnSimmons", birthdate: "1992", email: "finn.simmons@example.com" },
    { name: "GinaCook", birthdate: "1994", email: "gina.cook@example.com" },
    { name: "HarryRogers", birthdate: "1989", email: "harry.rogers@example.com" },
    { name: "IsabellaPatterson", birthdate: "1987", email: "isabella.patterson@example.com" },
    { name: "JakeButler", birthdate: "1990", email: "jake.butler@example.com" },
    { name: "KaraBailey", birthdate: "1993", email: "kara.bailey@example.com" },
    { name: "LeoCooper", birthdate: "1985", email: "leo.cooper@example.com" },
    { name: "MayaHoward", birthdate: "1998", email: "maya.howard@example.com" },
    { name: "NathanPeterson", birthdate: "1991", email: "nathan.peterson@example.com" },
    { name: "OlivePrice", birthdate: "1986", email: "olive.price@example.com" },
    { name: "PeterWard", birthdate: "1994", email: "peter.ward@example.com" },
    { name: "QuincyBrooks", birthdate: "1997", email: "quincy.brooks@example.com" },
    { name: "RitaBarnes", birthdate: "1989", email: "rita.barnes@example.com" },
    { name: "SteveHayes", birthdate: "1990", email: "steve.hayes@example.com" },
    { name: "TaraRoss", birthdate: "1995", email: "tara.ross@example.com" }
  ];
  
  // Export the list of user data
  module.exports = userDataList;
  